### PR TITLE
Added support for encoding D3D11 textures

### PR DESCRIPTION
**Pull request by ziriax**
I didn't have time to add a sample yet, but this might be a start.

### CODE REVIEW

**Comment by tbiedert** [comment]
Thanks! This looks quite nice already!

Would be great if you could add a very small sample to demonstrate and test it.

What about the decoding side?

**Comment by tbiedert** [comment]
It might also make sense to directly use NvCodec’s native Direct3D interface.  

I have used the CUDA-GL interop path for OpenGL, as NvCodec’s direct OpenGL Interface is currently only available on Linux.

**Comment by Ziriax** [comment]
We had too many problems with this approach in our setup, we were running on different threads and sometimes the D3D11 rendering was missing frames (only clearing, not rendering). Switch to the D3D11Encoder fixed our problems. So I will provide a new patch

**Comment by tbiedert** [comment]
I've just pushed an update, including Video Codec SDK 9 and some more fixes (5426f6b7fd72d27310b51a00ad439aba15446c50).

If you still want to add the DX11 interface to NvPipe, I suggest adding another flag to the encoder constructor, based on which the underlying encoder instance is chosen:
```
typedef enum {
    NVPIPE_CUDA_OPENGL,
    NVPIPE_D3D11
} NvPipe_EncoderType;
```

A short D3D11-based example similar to EGL would be awesome as well!

Thansk for your help!
Tim

**Comment by cnlohr** [comment]
Were you ever able to make a working instance taking on D3D11 textures?  I am still racking my brain against this one in the current environment.

**Comment by tbiedert** [comment]
@cnlohr I suggest you check out the latest Video Codec SDK. In particular the samples, which demonstrate various interop scenarios.

**Pull request closed without merging**
